# Task 2: Predicting severity metrics
Run this notebook to predict the severity (UPDRSM, H&Y, UPDRS). 

The structure of this notebook is as follows: 
1. Data setup: loading features, metadata, splits
2. Training helper: function to train models and save outputs
3. UPDRSM Prediction using our 4 models
4. Hoehn and Yahr Prediction using our 4 models
5. UPDRS Prediction using our 4 models 

Note: Further elaboration on our choice of predictors (between UPDRSM and UPDRS) is explained in the respective sections below. 

Our 4 models are: 
1. Mean baseline 
2. Multiple linear regression
3. Random Forest (+ Hyperparameter tuning)
4. 1D-CNN (+ Hyperparameter tuning)

For Random Forest and 1D-CNN, we use the same hyperparameters for each predictor to ensure consistency.

## 1. Data setup

In [1]:
# imports and setting file paths
from pathlib import Path
import sys
import json
import numpy as np
import pandas as pd
import joblib
from sklearn.dummy import DummyRegressor
import tensorflow as tf

ROOT = Path.cwd().resolve()
if not (ROOT / "src").is_dir():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

SPLITS_PATH = ROOT / "data" / "splits.json"

# output directory
OUT = ROOT / "presentation_material" / "task2"
(OUT / "predictions").mkdir(parents=True, exist_ok=True)
(OUT / "weights").mkdir(parents=True, exist_ok=True)

# import functions from models 
from src.data import load_metadata, col_names
from src.features import X as features
from src.models.linreg import make_linear_regression
from src.models.rf import make_random_forest
from src.models.cnn1d import build_cnn

print("Features shape:", features.shape)
display(features.head())

Features shape: (165, 5)

        stride_time  stride_cv  swing_cv  swing_asymmetry  peak_force
GaCo01     1.230322   0.042125  0.054223         0.013902   14.561747
GaCo02     1.103386   0.035667  0.037527         0.001486   15.233429
GaCo03     1.241191   0.049523  0.078598         0.103336   12.754554
GaCo04     1.249965   0.058603  0.064637         0.022956   15.401692
GaCo05     1.051882   0.039561  0.055866         0.013298   12.820625

In [2]:
# load data 
metadata = load_metadata().rename(columns={'ID':'subject'})
features = features.rename_axis('subject').reset_index()

# merge metadata and features into patients 
patients = features.merge(
    metadata[['subject','Group','UPDRSM', 'HoehnYahr', 'UPDRS']], 
    on='subject', how='inner', validate='many_to_one')
patients = patients.loc[
    patients['Group'].eq('Pt') 
    & patients['UPDRSM'].notna()
    & patients['HoehnYahr'].notna()
    & patients['UPDRS'].notna()
    ].reset_index(drop=True)



feature_columns = ['stride_time','stride_cv','swing_cv','swing_asymmetry','peak_force']

X = patients[feature_columns]
y_updrsm = patients['UPDRSM'].astype(float) # for UPDRSM prediction
y_hy = patients['HoehnYahr'].astype(float) # for Hoehn & Yahr prediction 
y_updrs = patients["UPDRS"].astype(float) # for UPDRS prediction

print("Patients:", patients["subject"].nunique(), "| Feature matrix:", X.shape)
display(
    patients[["subject", "UPDRSM", "HoehnYahr", "UPDRS"]].head()
)

Patients: 91 | Feature matrix: (91, 5)

  subject  UPDRSM  HoehnYahr  UPDRS
0  GaPt03    10.0        3.0   20.0
1  GaPt04     8.0        2.5   25.0
2  GaPt05     5.0        2.5   24.0
3  GaPt06    13.0        2.0   16.0
4  GaPt07    22.0        3.0   44.0

In [ ]:
with open(SPLITS_PATH) as f:
    assignment = json.load(f)["task2"]

test_subjects = set(assignment["test"])
folds = []
for fold in assignment["folds"]:
    train_ids, val_ids = set(fold["train"]), set(fold["val"])
    
    # safety check: keep the held-out test subjects separate.
    assert train_ids.isdisjoint(val_ids | test_subjects) and val_ids.isdisjoint(test_subjects)
    train_idx = np.flatnonzero(patients["subject"].isin(train_ids).to_numpy())
    val_idx = np.flatnonzero(patients["subject"].isin(val_ids).to_numpy())
    folds.append((train_idx, val_idx))

print('CV folds:',len(folds),'held-out test subjects:',len(test_subjects))

CV folds: 5 held-out test subjects: 19
Using 5 saved validation folds; held-out test subjects untouched.

## 2. Training helper

Function to implement at every model to train the model and save the output.

In [4]:
def train_and_save(model_name, make_model, y_target, target_name):
    for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):
        model = make_model()  
        model.fit(X.iloc[train_idx], 
                  y_target.iloc[train_idx])  # train only on training subjects
        predictions = np.asarray(model.predict(X.iloc[val_idx])).reshape(-1)

        # Save actual values and predictions for the results teammate.
        output = pd.DataFrame({
            "subject": patients.iloc[val_idx]["subject"].to_numpy(),
            "fold": fold_number,
            f"actual_{target_name}": y_target.iloc[val_idx].to_numpy(),
            f"predicted_{target_name}": predictions
        })
        
        if target_name == "UPDRSM":
            filename = model_name
        else:
            filename = f"{model_name}_{target_name}"
            
        output.to_csv(
            OUT / "predictions" /
            f"{filename}_val_fold{fold_number}.csv",
            index=False
        )
        # save fitted preprocessing steps and model together
        joblib.dump(
            model,
            OUT / "weights" /
            f"{filename}_val_fold{fold_number}.joblib"
        )

        print(
            f"{model_name} ({target_name}): "
            f"fold {fold_number} saved"
        )
    # final model: train on all CV patients, predict the held-out test patients once
    tv = np.flatnonzero(~patients["subject"].isin(test_subjects).to_numpy())
    te = np.flatnonzero(patients["subject"].isin(test_subjects).to_numpy())
    model = make_model()
    model.fit(X.iloc[tv], y_target.iloc[tv])
    pd.DataFrame({
        "subject": patients.iloc[te]["subject"].to_numpy(),
        f"actual_{target_name}": y_target.iloc[te].to_numpy(),
        f"predicted_{target_name}": np.asarray(model.predict(X.iloc[te])).reshape(-1)
    }).to_csv(OUT / "predictions" / f"{filename}_test.csv", index=False)
    joblib.dump(model, OUT / "weights" / f"{filename}_test.joblib")
    print(f"{model_name}: model train complete")

## 3. UPDRSM Predictions

Models: 
1. Mean baseline. This is used as a reference point. We will compare our model performance with this baseline. 
2. Multiple Linear Regression
3. Random Forest (+ Hyperparameter tuning)
4. 1D-CNN (+ Hyperparameter tuning)

We choose UPDRSM instead of UPDRS as our primary predictor because UPDRSM measures motor impairment specifically, which focuses on motor function, more closely related to the physical signals recorded in our dataset and chosen as our features.

In [5]:
train_and_save("mean_baseline", lambda: DummyRegressor(strategy="mean"),
               y_updrsm, "UPDRSM")

mean_baseline (UPDRSM): fold 1 saved
mean_baseline (UPDRSM): fold 2 saved
mean_baseline (UPDRSM): fold 3 saved
mean_baseline (UPDRSM): fold 4 saved
mean_baseline (UPDRSM): fold 5 saved
mean_baseline: model train complete

In [6]:
train_and_save("linear_regression", make_linear_regression,
               y_updrsm, "UPDRSM")

linear_regression (UPDRSM): fold 1 saved
linear_regression (UPDRSM): fold 2 saved
linear_regression (UPDRSM): fold 3 saved
linear_regression (UPDRSM): fold 4 saved
linear_regression (UPDRSM): fold 5 saved
linear_regression: model train complete

In [7]:
train_and_save("random_forest", make_random_forest, 
               y_updrsm, "UPDRSM")

random_forest (UPDRSM): fold 1 saved
random_forest (UPDRSM): fold 2 saved
random_forest (UPDRSM): fold 3 saved
random_forest (UPDRSM): fold 4 saved
random_forest (UPDRSM): fold 5 saved
random_forest: model train complete

In [8]:
# hyperparameter tuning 

from sklearn.model_selection import ParameterGrid
from sklearn.metrics import mean_squared_error

# combinations to test
param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [3, 5, None],
    "model__min_samples_leaf": [2, 5]
}

tuning_results = [] # store results

for params in ParameterGrid(param_grid):
    squared_errors = []
    
    for train_idx, val_idx in folds:
        # create new model and apply parameter combination 
        model = make_random_forest() 
        model.set_params(**params) 
        model.fit(X.iloc[train_idx], y_updrsm.iloc[train_idx])
        predictions = model.predict(X.iloc[val_idx])
        
        # alculate squared errors for every validation patient
        errors = (y_updrsm.iloc[val_idx].to_numpy() - predictions)
        squared_errors.extend(errors ** 2)
        
    # calculate average validation RMSE across five folds.
    tuning_results.append({
        **params,
        "pooled_RMSE": np.sqrt(np.mean(squared_errors))
    })

rf_tuning = pd.DataFrame(tuning_results)
rf_tuning = rf_tuning.sort_values("pooled_RMSE")
display(rf_tuning)

print("Best RF hyperparameters:")
display(rf_tuning.head(1))

,model__max_depth,model__min_samples_leaf,model__n_estimators,pooled_RMSE
7,5.0,5,200,8.197110
11,NaN,5,200,8.197284
3,3.0,5,200,8.216156
10,NaN,5,100,8.284667
1,3.0,2,200,8.284745
6,5.0,5,100,8.285509
2,3.0,5,100,8.293199
0,3.0,2,100,8.346316
5,5.0,2,200,8.386064
9,NaN,2,200,8.392528
4,5.0,2,100,8.491420
8,NaN,2,100,8.502082

Best RF hyperparameters:

   model__max_depth  model__min_samples_leaf  model__n_estimators  pooled_RMSE
7               5.0                        5                  200      8.19711

In [9]:
# with tuned hyperparameters
def make_tuned_rf(): # use same hyperparameter tuning for clean comparison between UPDRSM and HY
    model = make_random_forest(
        task="regression",
        n_estimators=200, 
        min_samples_leaf=5,  
        random_state=42
    )
    model.set_params(model__max_depth=5) 
    return model

train_and_save("random_forest_tuned", make_tuned_rf, y_updrsm, "UPDRSM")

random_forest_tuned (UPDRSM): fold 1 saved
random_forest_tuned (UPDRSM): fold 2 saved
random_forest_tuned (UPDRSM): fold 3 saved
random_forest_tuned (UPDRSM): fold 4 saved
random_forest_tuned (UPDRSM): fold 5 saved
random_forest_tuned: model train complete

In [10]:
# 10-second starting window 
# 16 force sensor channels 
PROCESSED = ROOT/'data'/'processed'
RAW = ROOT/'data'/'raw'
TIME_STEPS = 1000
SENSOR_COLS = [f'L{i}' for i in range(1,9)] + [f'R{i}' for i in range(1,9)]

def load_signal(subject):
    csv_path = PROCESSED/f'{subject}_01.csv'
    txt_path = RAW/f'{subject}_01.txt'
    if csv_path.exists():
        walk = pd.read_csv(csv_path)
    else:
        walk = pd.read_csv(txt_path,sep=r'\s+',header=None,names=col_names)
    signal = walk[SENSOR_COLS].iloc[:TIME_STEPS].to_numpy(dtype=np.float32)
    if signal.shape != (TIME_STEPS,16) or not np.isfinite(signal).all():
        raise ValueError(f'Invalid CNN signal for {subject}: {signal.shape}')
    return signal

signals = np.stack([load_signal(subject) for subject in patients['subject']])
print('CNN input shape (subjects, time steps, channels):',signals.shape)

CNN input shape (subjects, time steps, channels): (91, 1000, 16)

In [11]:
# train CNN model per fold, saving predictions and weights for each
import tensorflow as tf
EPOCHS = 20
BATCH_SIZE = 16

def train_cnn_and_save(model_name, y_target, target_name, learning_rate, epochs):
    if target_name == "UPDRSM":
        filename = model_name
    else:
        filename = f"{model_name}_{target_name}"

    for fold_number, (train_idx, val_idx) in enumerate(folds, 1):
        tf.keras.utils.set_random_seed(42)
        # normalise signals
        mean = signals[train_idx].mean(axis=(0, 1), keepdims=True)
        std = np.maximum(signals[train_idx].std(axis=(0, 1), keepdims=True), 1e-6)
        x_train = (signals[train_idx] - mean) / std
        x_val = (signals[val_idx] - mean) / std

        # create and train model for each fold
        model = build_cnn(input_shape=(TIME_STEPS, 16), task="regression", learning_rate=learning_rate)
        model.fit(x_train, y_target.iloc[train_idx].to_numpy(),
                  epochs=epochs, batch_size=BATCH_SIZE, verbose=1)
        predicted = model.predict(x_val, verbose=0).reshape(-1)

        # save predictions and model weights
        pd.DataFrame({"subject": patients.iloc[val_idx]["subject"].to_numpy(),
                      "fold": fold_number,
                      f"actual_{target_name}": y_target.iloc[val_idx].to_numpy(),
                      f"predicted_{target_name}": predicted}).to_csv(
            OUT / "predictions" / f"{filename}_val_fold{fold_number}.csv", index=False)
        model.save(OUT / "weights" / f"{filename}_val_fold{fold_number}.keras")
        np.savez(OUT / "weights" / f"{filename}_val_fold{fold_number}_normalisation.npz",
                 mean=mean, std=std, time_steps=TIME_STEPS, sensor_columns=np.array(SENSOR_COLS))
        print(f"{filename}: fold {fold_number} saved")

    # final model: train on all CV patients, predict the held-out test patients once
    tf.keras.utils.set_random_seed(42)
    tv = np.flatnonzero(~patients["subject"].isin(test_subjects).to_numpy())
    te = np.flatnonzero(patients["subject"].isin(test_subjects).to_numpy())
    mean = signals[tv].mean(axis=(0, 1), keepdims=True)
    std = np.maximum(signals[tv].std(axis=(0, 1), keepdims=True), 1e-6)
    model = build_cnn(input_shape=(TIME_STEPS, 16), task="regression", learning_rate=learning_rate)
    model.fit((signals[tv] - mean) / std, y_target.iloc[tv].to_numpy(),
              epochs=epochs, batch_size=BATCH_SIZE, verbose=0)
    pd.DataFrame({"subject": patients.iloc[te]["subject"].to_numpy(),
                  f"actual_{target_name}": y_target.iloc[te].to_numpy(),
                  f"predicted_{target_name}": model.predict((signals[te] - mean) / std, verbose=0).reshape(-1)}).to_csv(
        OUT / "predictions" / f"{filename}_test.csv", index=False)
    model.save(OUT / "weights" / f"{filename}_test.keras")
    np.savez(OUT / "weights" / f"{filename}_test_normalisation.npz",
             mean=mean, std=std, time_steps=TIME_STEPS, sensor_columns=np.array(SENSOR_COLS))
    print(f"{filename}: test set saved")

train_cnn_and_save("cnn", y_updrsm, "UPDRSM", 0.001, EPOCHS)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 410.5540 - mae: 18.5496
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 383.5503 - mae: 17.7956
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 352.5683 - mae: 16.8850
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 314.0274 - mae: 15.6758
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 266.4514 - mae: 14.0876
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 211.2264 - mae: 12.1071
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.8764 - mae: 9.7495
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106.0469 - mae: 7.6712
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 82.7157 - mae: 7.1103
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.1473 - mae: 7.5378
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 86.7039 - mae: 7.7381
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 80.5525 - mae: 7.3755
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.5764 - mae: 6.9967
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.6078 - mae: 6.8723
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.2391 - mae: 6.8925
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.5985 - mae: 6.8856
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 76.4795 - mae: 6.8416
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 74.9617 - mae: 6.8114
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.8454 - mae: 6.8073
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.1565 - mae: 6.8176
cnn: fold 1 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 403.3992 - mae: 18.2852
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 377.0907 - mae: 17.5448
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 346.6328 - mae: 16.6428
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 308.4599 - mae: 15.4368
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 261.4423 - mae: 13.8351
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 206.9677 - mae: 11.8485
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.2887 - mae: 9.6546
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 102.8229 - mae: 7.6781
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 80.0249 - mae: 6.9733
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 82.7379 - mae: 7.4599
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 85.1617 - mae: 7.5729
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.7009 - mae: 7.1278
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.6804 - mae: 6.7406
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.4847 - mae: 6.6859
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.4694 - mae: 6.7328
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.6014 - mae: 6.7140
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 74.1958 - mae: 6.6487
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.7114 - mae: 6.6372
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.8323 - mae: 6.6644
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.2914 - mae: 6.6704
cnn: fold 2 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 444.5095 - mae: 19.5613
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 415.2758 - mae: 18.8003
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 381.0056 - mae: 17.8646
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 338.4373 - mae: 16.6299
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 285.6765 - mae: 14.9565
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 223.7254 - mae: 12.7808
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 158.0451 - mae: 10.2906
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.8757 - mae: 7.7485
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 70.7414 - mae: 6.6134
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 75.7930 - mae: 7.0115
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.7670 - mae: 7.6096
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 85.0122 - mae: 7.4841
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 76.0019 - mae: 7.0278
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.3072 - mae: 6.7437
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.0376 - mae: 6.6254
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.4513 - mae: 6.5810
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.8875 - mae: 6.5427
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.5380 - mae: 6.5536
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.1951 - mae: 6.5941
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.4341 - mae: 6.6295
cnn: fold 3 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 396.4901 - mae: 18.5376
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 369.0831 - mae: 17.7794
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 337.2394 - mae: 16.8564
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 297.5208 - mae: 15.6289
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 248.6156 - mae: 13.9753
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 191.7851 - mae: 11.9176
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 132.6240 - mae: 9.4741
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 83.3315 - mae: 7.1684
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.1195 - mae: 6.2850
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.5124 - mae: 6.9643
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.5232 - mae: 7.3587
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.4800 - mae: 7.0797
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5045 - mae: 6.5957
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.4130 - mae: 6.2481
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.1567 - mae: 6.1478
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.4314 - mae: 6.0901
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0379 - mae: 6.0592
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1205 - mae: 6.1030
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.0820 - mae: 6.1728
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.2374 - mae: 6.2119
cnn: fold 4 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 410.2703 - mae: 18.5936
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 382.8695 - mae: 17.8328
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 350.9016 - mae: 16.8976
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 311.3721 - mae: 15.6625
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 262.7931 - mae: 14.0000
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 206.4868 - mae: 11.9926
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 148.1342 - mae: 9.8763
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 99.8517 - mae: 7.8582
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.0587 - mae: 7.0948
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 83.8636 - mae: 7.4602
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.2026 - mae: 7.7660
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 82.1400 - mae: 7.4309
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.4994 - mae: 7.0589
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 74.4469 - mae: 6.9537
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.3067 - mae: 6.9580
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.0496 - mae: 6.9260
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.6766 - mae: 6.8483
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.4118 - mae: 6.8109
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.8367 - mae: 6.8355
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.5660 - mae: 6.8523
WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x1280c6340> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
cnn: fold 5 saved
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x127b4a5c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
cnn: test set saved

In [12]:
# hyperparameter tuning 
learning_rates = [0.001, 0.0001]
epoch_options = [10, 20, 30]

cnn_tuning_results = []

for learning_rate in learning_rates:
    for epochs in epoch_options:

        squared_errors = []
        
        for fold_number, (train_idx, val_idx) in enumerate(folds):
            tf.keras.utils.set_random_seed(42)

            # nomralisation
            mean = signals[train_idx].mean(axis=(0, 1), keepdims=True)
            std = np.maximum(signals[train_idx].std(axis=(0, 1), keepdims=True), 1e-6)
            x_train = (signals[train_idx] - mean) / std
            x_val = (signals[val_idx] - mean) / std

            # build and train new cnn
            model = build_cnn(
                input_shape=(TIME_STEPS, 16),
                task="regression",
                learning_rate=learning_rate)
            
            model.fit(x_train, y_updrsm.iloc[train_idx].to_numpy(),
                epochs=epochs, batch_size=16, verbose=0)

            # generate validation predictions
            predictions = model.predict(x_val, verbose=0).reshape(-1)

            # calculate validation RMSE
            # Accumulate individual validation squared errors.
            errors = (y_updrsm.iloc[val_idx].to_numpy() - predictions)
            squared_errors.extend(errors ** 2)

        cnn_tuning_results.append({
            "learning_rate": learning_rate,
            "epochs": epochs,
            "pooled_RMSE": np.sqrt(np.mean(squared_errors))
        })

# compare configurations
cnn_tuning = pd.DataFrame(cnn_tuning_results)
cnn_tuning = cnn_tuning.sort_values("pooled_RMSE")

display(cnn_tuning)

print("Best CNN configuration:")
display(cnn_tuning.head(1))

   learning_rate  epochs  pooled_RMSE
1         0.0010      20     8.768448
2         0.0010      30     8.772256
0         0.0010      10     9.550545
5         0.0001      30    17.122664
4         0.0001      20    18.795890
3         0.0001      10    19.839288

Best CNN configuration:

   learning_rate  epochs  pooled_RMSE
1          0.001      20     8.768448

In [13]:
# CNN with tuned hyperparameters (best row of the tuning table above)
TUNED_LEARNING_RATE = float(cnn_tuning.iloc[0]["learning_rate"])
TUNED_EPOCHS = int(cnn_tuning.iloc[0]["epochs"])

train_cnn_and_save("cnn_tuned", y_updrsm, "UPDRSM", TUNED_LEARNING_RATE, TUNED_EPOCHS)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 410.5540 - mae: 18.5496
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 383.5503 - mae: 17.7956
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 352.5683 - mae: 16.8850
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 314.0274 - mae: 15.6758
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 266.4514 - mae: 14.0876
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 211.2264 - mae: 12.1071
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.8764 - mae: 9.7495
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.0469 - mae: 7.6712
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 82.7157 - mae: 7.1103
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 84.1473 - mae: 7.5378
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 86.7039 - mae: 7.7381
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 80.5525 - mae: 7.3755
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.5764 - mae: 6.9967
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.6078 - mae: 6.8723
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.2391 - mae: 6.8925
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.5985 - mae: 6.8856
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 76.4795 - mae: 6.8416
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 74.9617 - mae: 6.8114
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.8454 - mae: 6.8073
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.1565 - mae: 6.8176
cnn_tuned: fold 1 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 403.3992 - mae: 18.2852
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 377.0907 - mae: 17.5448
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 346.6328 - mae: 16.6428
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 308.4599 - mae: 15.4368
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 261.4423 - mae: 13.8351
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 206.9677 - mae: 11.8485
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 150.2887 - mae: 9.6546
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 102.8229 - mae: 7.6781
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 80.0249 - mae: 6.9733
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 82.7379 - mae: 7.4599
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 85.1617 - mae: 7.5729
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.7009 - mae: 7.1278
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.6804 - mae: 6.7406
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.4847 - mae: 6.6859
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.4694 - mae: 6.7328
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.6014 - mae: 6.7140
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 74.1958 - mae: 6.6487
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.7114 - mae: 6.6372
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.8323 - mae: 6.6644
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.2914 - mae: 6.6704
cnn_tuned: fold 2 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 444.5095 - mae: 19.5613
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 415.2758 - mae: 18.8003
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 381.0056 - mae: 17.8646
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 338.4373 - mae: 16.6299
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 285.6765 - mae: 14.9565
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 223.7254 - mae: 12.7808
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 158.0451 - mae: 10.2906
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.8757 - mae: 7.7485
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 70.7414 - mae: 6.6134
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.7930 - mae: 7.0115
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 88.7670 - mae: 7.6096
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 85.0122 - mae: 7.4841
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 76.0019 - mae: 7.0278
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.3072 - mae: 6.7437
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.0376 - mae: 6.6254
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.4513 - mae: 6.5810
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.8875 - mae: 6.5427
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.5380 - mae: 6.5536
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.1951 - mae: 6.5941
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.4341 - mae: 6.6295
cnn_tuned: fold 3 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 396.4901 - mae: 18.5376
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 369.0831 - mae: 17.7794
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 337.2394 - mae: 16.8564
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 297.5208 - mae: 15.6289
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 248.6156 - mae: 13.9753
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.7851 - mae: 11.9176
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 132.6240 - mae: 9.4741
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 83.3315 - mae: 7.1684
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 61.1195 - mae: 6.2850
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.5124 - mae: 6.9643
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 78.5232 - mae: 7.3587
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.4800 - mae: 7.0797
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 62.5045 - mae: 6.5957
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 59.4130 - mae: 6.2481
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 59.1567 - mae: 6.1478
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 58.4314 - mae: 6.0901
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 57.0379 - mae: 6.0592
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56.1205 - mae: 6.1030
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56.0820 - mae: 6.1728
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56.2374 - mae: 6.2119
cnn_tuned: fold 4 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 410.2703 - mae: 18.5936
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 382.8695 - mae: 17.8328
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 350.9016 - mae: 16.8976
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 311.3721 - mae: 15.6625
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 262.7931 - mae: 14.0000
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 206.4868 - mae: 11.9926
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.1342 - mae: 9.8763
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.8517 - mae: 7.8582
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 78.0587 - mae: 7.0948
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 83.8636 - mae: 7.4602
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 89.2026 - mae: 7.7660
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 82.1400 - mae: 7.4309
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.4994 - mae: 7.0589
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 74.4469 - mae: 6.9537
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.3067 - mae: 6.9580
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.0496 - mae: 6.9260
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.6766 - mae: 6.8483
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.4118 - mae: 6.8109
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.8367 - mae: 6.8355
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.5660 - mae: 6.8523
cnn_tuned: fold 5 saved
cnn_tuned: test set saved

## 4. Hoehn and Yahr Prediction

The models used for Hoehn and Yahr prediction are the same as for UPDRSM.

In [14]:
# mean baseline 
train_and_save("mean_baseline", lambda: DummyRegressor(strategy="mean"), 
               y_hy, "HoehnYahr")

mean_baseline (HoehnYahr): fold 1 saved
mean_baseline (HoehnYahr): fold 2 saved
mean_baseline (HoehnYahr): fold 3 saved
mean_baseline (HoehnYahr): fold 4 saved
mean_baseline (HoehnYahr): fold 5 saved
mean_baseline: model train complete

In [15]:
# MLR 
train_and_save("linear_regression", make_linear_regression,
                y_hy, "HoehnYahr")

linear_regression (HoehnYahr): fold 1 saved
linear_regression (HoehnYahr): fold 2 saved
linear_regression (HoehnYahr): fold 3 saved
linear_regression (HoehnYahr): fold 4 saved
linear_regression (HoehnYahr): fold 5 saved
linear_regression: model train complete

In [16]:
train_and_save("random_forest", make_tuned_rf,
                y_hy, "HoehnYahr")

random_forest (HoehnYahr): fold 1 saved
random_forest (HoehnYahr): fold 2 saved
random_forest (HoehnYahr): fold 3 saved
random_forest (HoehnYahr): fold 4 saved
random_forest (HoehnYahr): fold 5 saved
random_forest: model train complete

In [17]:
# CNN
train_cnn_and_save("cnn", y_hy, "HoehnYahr", TUNED_LEARNING_RATE, TUNED_EPOCHS)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.8779 - mae: 1.9192
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6274 - mae: 1.1672
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4681 - mae: 0.5127
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5127 - mae: 0.6064
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4791 - mae: 0.6011
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2612 - mae: 0.4005
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2360 - mae: 0.3626
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2883 - mae: 0.3970
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2870 - mae: 0.3926
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2469 - mae: 0.3670
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2229 - mae: 0.3638
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2153 - mae: 0.3618
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2004 - mae: 0.3526
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1883 - mae: 0.3395
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1878 - mae: 0.3328
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1869 - mae: 0.3298
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1803 - mae: 0.3274
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1725 - mae: 0.3262
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1653 - mae: 0.3236
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1588 - mae: 0.3180
cnn_HoehnYahr: fold 1 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.6913 - mae: 1.8816
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5056 - mae: 1.1392
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3829 - mae: 0.4651
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4940 - mae: 0.5829
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4433 - mae: 0.5432
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2264 - mae: 0.3644
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2045 - mae: 0.3593
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2408 - mae: 0.3873
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2314 - mae: 0.3777
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1983 - mae: 0.3518
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1855 - mae: 0.3413
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1815 - mae: 0.3354
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1682 - mae: 0.3254
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1600 - mae: 0.3212
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1595 - mae: 0.3204
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1561 - mae: 0.3164
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1495 - mae: 0.3114
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1436 - mae: 0.3075
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1381 - mae: 0.3039
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1335 - mae: 0.2994
cnn_HoehnYahr: fold 2 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.7711 - mae: 1.9026
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5153 - mae: 1.1462
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3652 - mae: 0.4818
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5603 - mae: 0.6286
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5567 - mae: 0.6099
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2886 - mae: 0.4126
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2603 - mae: 0.3899
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2837 - mae: 0.4096
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2512 - mae: 0.3824
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2151 - mae: 0.3602
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2160 - mae: 0.3656
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2161 - mae: 0.3671
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1979 - mae: 0.3516
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1865 - mae: 0.3407
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1817 - mae: 0.3337
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1740 - mae: 0.3291
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1678 - mae: 0.3279
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1640 - mae: 0.3293
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1584 - mae: 0.3243
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1529 - mae: 0.3163
cnn_HoehnYahr: fold 3 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.9323 - mae: 1.9355
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6487 - mae: 1.1848
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4565 - mae: 0.5211
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5539 - mae: 0.6227
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5642 - mae: 0.6408
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3005 - mae: 0.4410
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2296 - mae: 0.3592
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2588 - mae: 0.3768
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2621 - mae: 0.3814
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2352 - mae: 0.3684
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2201 - mae: 0.3636
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2203 - mae: 0.3691
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2106 - mae: 0.3619
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1944 - mae: 0.3445
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1864 - mae: 0.3367
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1837 - mae: 0.3333
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1797 - mae: 0.3309
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1750 - mae: 0.3302
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1707 - mae: 0.3292
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1655 - mae: 0.3250
cnn_HoehnYahr: fold 4 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.8081 - mae: 1.9143
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5319 - mae: 1.1589
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3536 - mae: 0.4735
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5357 - mae: 0.6016
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5499 - mae: 0.6163
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2758 - mae: 0.4052
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2335 - mae: 0.3664
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2521 - mae: 0.3819
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2306 - mae: 0.3714
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1980 - mae: 0.3514
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1941 - mae: 0.3496
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1961 - mae: 0.3488
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1819 - mae: 0.3354
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1692 - mae: 0.3271
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1637 - mae: 0.3227
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1572 - mae: 0.3170
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1508 - mae: 0.3122
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1468 - mae: 0.3094
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1423 - mae: 0.3054
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1368 - mae: 0.2991
cnn_HoehnYahr: fold 5 saved
cnn_HoehnYahr: test set saved

## 5. UPDRS Prediction

UPDRS captures overall disease, including non-motor dimensions which are not captured in our dataset. This is an additional experiment to investigate if gait can predict overall disease instead of specifically predicting motor impairment.

In [18]:
# mean baseline 
train_and_save("mean_baseline", lambda: DummyRegressor(strategy="mean"), 
               y_updrs, "UPDRS")

mean_baseline (UPDRS): fold 1 saved
mean_baseline (UPDRS): fold 2 saved
mean_baseline (UPDRS): fold 3 saved
mean_baseline (UPDRS): fold 4 saved
mean_baseline (UPDRS): fold 5 saved
mean_baseline: model train complete

In [19]:
# MLR 
train_and_save("linear_regression", make_linear_regression,
                y_updrs, "UPDRS")

linear_regression (UPDRS): fold 1 saved
linear_regression (UPDRS): fold 2 saved
linear_regression (UPDRS): fold 3 saved
linear_regression (UPDRS): fold 4 saved
linear_regression (UPDRS): fold 5 saved
linear_regression: model train complete

In [20]:
# RF
train_and_save("random_forest", make_tuned_rf,
                y_updrs, "UPDRS")

random_forest (UPDRS): fold 1 saved
random_forest (UPDRS): fold 2 saved
random_forest (UPDRS): fold 3 saved
random_forest (UPDRS): fold 4 saved
random_forest (UPDRS): fold 5 saved
random_forest: model train complete

In [21]:
# CNN
train_cnn_and_save("cnn", y_updrs, "UPDRS", TUNED_LEARNING_RATE, TUNED_EPOCHS)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1107.3313 - mae: 31.0401
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1061.2684 - mae: 30.2793
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1006.7998 - mae: 29.3520
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 937.0504 - mae: 28.1195
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 846.8492 - mae: 26.4378
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 733.5305 - mae: 24.1512
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 597.9158 - mae: 21.0752
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 448.5745 - mae: 17.0429
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 307.0995 - mae: 13.0349
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 208.2518 - mae: 10.5506
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 179.0993 - mae: 10.4712
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 191.2749 - mae: 11.3599
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 187.7335 - mae: 11.2973
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 169.0754 - mae: 10.4120
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 160.0199 - mae: 9.7992
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 162.3919 - mae: 9.6356
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 166.2462 - mae: 9.6176
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 166.1040 - mae: 9.5834
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 162.7649 - mae: 9.5342
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 159.0788 - mae: 9.4862
cnn_UPDRS: fold 1 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1083.5750 - mae: 30.4246
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1039.0122 - mae: 29.6803
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 986.1749 - mae: 28.7703
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 917.9766 - mae: 27.5521
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 830.0995 - mae: 25.8963
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 720.0690 - mae: 23.6551
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 588.5843 - mae: 20.6504
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 443.5364 - mae: 16.7486
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 305.1111 - mae: 12.8834
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 206.1918 - mae: 10.5602
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.7690 - mae: 10.5670
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 187.5331 - mae: 11.5100
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 186.0813 - mae: 11.5011
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 167.1354 - mae: 10.6449
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 157.1324 - mae: 9.8884
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 159.4835 - mae: 9.7071
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 163.8044 - mae: 9.6649
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 164.0275 - mae: 9.6863
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 160.9501 - mae: 9.7177
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 157.6268 - mae: 9.7813
cnn_UPDRS: fold 2 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1181.0353 - mae: 32.0779
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1132.1956 - mae: 31.3124
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1073.6583 - mae: 30.3682
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 998.6536 - mae: 29.1161
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 901.5201 - mae: 27.4097
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 779.1823 - mae: 25.0926
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 632.3379 - mae: 21.9849
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 469.1647 - mae: 17.9476
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 311.0987 - mae: 13.6340
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 194.9584 - mae: 10.4083
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 158.6290 - mae: 9.8010
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 188.6407 - mae: 11.2089
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 207.0954 - mae: 11.9809
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 190.1612 - mae: 11.2986
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171.5580 - mae: 10.4631
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 165.7538 - mae: 9.9352
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 165.6004 - mae: 9.7937
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 164.0209 - mae: 9.7510
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 160.6374 - mae: 9.6705
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 158.1359 - mae: 9.7146
cnn_UPDRS: fold 3 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1098.0618 - mae: 30.9343
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1051.9690 - mae: 30.1785
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 997.4852 - mae: 29.2630
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 927.1288 - mae: 28.0398
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 836.2384 - mae: 26.3755
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 722.0664 - mae: 24.1190
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 585.3992 - mae: 21.0949
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 434.1850 - mae: 17.1161
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 288.6592 - mae: 13.2185
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 183.6379 - mae: 10.3861
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 153.7285 - mae: 9.9020
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.8434 - mae: 11.2436
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 198.0537 - mae: 11.7526
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 179.3418 - mae: 11.0582
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 158.6212 - mae: 10.2405
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 150.3412 - mae: 9.8219
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 148.4623 - mae: 9.6323
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 146.3241 - mae: 9.5163
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 143.1364 - mae: 9.4630
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 140.9319 - mae: 9.4831
cnn_UPDRS: fold 4 saved
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1114.4413 - mae: 31.1972
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1067.6099 - mae: 30.4328
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1011.6729 - mae: 29.4911
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 939.9986 - mae: 28.2400
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 847.4272 - mae: 26.5366
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 731.1133 - mae: 24.2211
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 591.9839 - mae: 21.1083
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 438.4238 - mae: 17.1222
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 292.5277 - mae: 13.2939
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.2289 - mae: 10.5350
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 167.4015 - mae: 10.3247
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 193.7923 - mae: 11.6268
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 197.3285 - mae: 11.8358
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 174.8079 - mae: 11.0328
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 160.1156 - mae: 10.2467
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 158.7876 - mae: 9.9539
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 160.1203 - mae: 9.9302
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 158.2644 - mae: 9.8398
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 154.6495 - mae: 9.7159
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.3459 - mae: 9.7383
cnn_UPDRS: fold 5 saved
cnn_UPDRS: test set saved