# Task 2: Predicting severity metrics
Run this notebook to predict the severity (UPDRSM). 

The structure of this notebook is as follows: 
1. Data setup: loading features, metadata, splits
2. Training helper: function to train models and save outputs
3. Mean baseline 
4. Multiple linear regression
5. Random forest
6. 1D-CNN

## 1. Data setup

In [1]:
# imports and setting file paths
from pathlib import Path
import sys
import json
import numpy as np
import pandas as pd
import joblib
from sklearn.dummy import DummyRegressor
import tensorflow as tf

ROOT = Path.cwd().resolve()
if not (ROOT / "src").is_dir():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

SPLITS_PATH = ROOT / "data" / "splits.json"

# output directory
OUT = ROOT / "presentation_material" / "task2"
(OUT / "predictions").mkdir(parents=True, exist_ok=True)
(OUT / "weights").mkdir(parents=True, exist_ok=True)

# import functions from models 
from src.data import load_metadata, col_names
from src.features import X as features
from src.models.linreg import make_linear_regression
from src.models.rf import make_random_forest
from src.models.cnn1d import build_cnn

print("Features shape:", features.shape)
display(features.head())

Features shape: (165, 5)

        stride_time  stride_cv  swing_cv  swing_asymmetry  peak_force
GaCo01     1.230322   0.042125  0.054223         0.013902   14.561747
GaCo02     1.103386   0.035667  0.037527         0.001486   15.233429
GaCo03     1.241191   0.049523  0.078598         0.103336   12.754554
GaCo04     1.249965   0.058603  0.064637         0.022956   15.401692
GaCo05     1.051882   0.039561  0.055866         0.013298   12.820625

In [2]:
# load data 
metadata = load_metadata().rename(columns={'ID':'subject'})
features = features.rename_axis('subject').reset_index()

# merge metadata and features into patients 
patients = features.merge(
    metadata[['subject','Group','UPDRSM', 'HoehnYahr']], 
    on='subject', how='inner', validate='many_to_one')
patients = patients.loc[
    patients['Group'].eq('Pt') 
    & patients['UPDRSM'].notna()
    & patients['HoehnYahr'].notna()
    ].reset_index(drop=True)

feature_columns = ['stride_time','stride_cv','swing_cv','swing_asymmetry','peak_force']

X = patients[feature_columns]
y_updrsm = patients['UPDRSM'].astype(float) # for UPDRSM prediction
y_hy = patients['HoehnYahr'].astype(float) # for Hoehn & Yahr prediction 

print("Patients:", patients["subject"].nunique(), "| Feature matrix:", X.shape)
display(
    patients[["subject", "UPDRSM", "HoehnYahr"]].head()
)

Patients: 91 | Feature matrix: (91, 5)

  subject  UPDRSM  HoehnYahr
0  GaPt03    10.0        3.0
1  GaPt04     8.0        2.5
2  GaPt05     5.0        2.5
3  GaPt06    13.0        2.0
4  GaPt07    22.0        3.0

In [3]:
with open(SPLITS_PATH) as f:
    assignment = json.load(f)["task2"]

test_subjects = set(assignment["test"])
folds = []
for fold in assignment["folds"]:
    train_ids, val_ids = set(fold["train"]), set(fold["val"])
    
    # safety check: keep the held-out test subjects separate.
    assert train_ids.isdisjoint(val_ids | test_subjects) and val_ids.isdisjoint(test_subjects)
    train_idx = np.flatnonzero(patients["subject"].isin(train_ids).to_numpy())
    val_idx = np.flatnonzero(patients["subject"].isin(val_ids).to_numpy())
    folds.append((train_idx, val_idx))

print('CV folds:',len(folds),'held-out test subjects:',len(test_subjects))
print("Using", len(folds), "saved validation folds; held-out test subjects untouched.")

CV folds: 5 held-out test subjects: 19
Using 5 saved validation folds; held-out test subjects untouched.

## 2. Training helper

Function to implement at every model to train the model and save the output.

In [4]:
def train_and_save(model_name, make_model, y_target, target_name):
    for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):
        model = make_model()  
        model.fit(X.iloc[train_idx], 
                  y_target.iloc[train_idx])  # train only on training subjects
        predictions = np.asarray(model.predict(X.iloc[val_idx])).reshape(-1)

        # Save actual values and predictions for the results teammate.
        output = pd.DataFrame({
            "subject": patients.iloc[val_idx]["subject"].to_numpy(),
            "fold": fold_number,
            f"actual_{target_name}": y_target.iloc[val_idx].to_numpy(),
            f"predicted_{target_name}": predictions
        })
        
        if target_name == "UPDRSM":
            filename = model_name
        else:
            filename = f"{model_name}_{target_name}"
            
        output.to_csv(
            OUT / "predictions" /
            f"{filename}_val_fold{fold_number}.csv",
            index=False
        )
        # save fitted preprocessing steps and model together
        joblib.dump(
            model,
            OUT / "weights" /
            f"{filename}_val_fold{fold_number}.joblib"
        )

        print(
            f"{model_name} ({target_name}): "
            f"fold {fold_number} saved"
        )
    print(f"{model_name}: model train complete")

## 3. Mean baseline 
This is used as a reference point. We will compare our model performance with this baseline.

In [5]:
train_and_save("mean_baseline", lambda: DummyRegressor(strategy="mean"),
               y_updrsm, "UPDRSM")

mean_baseline (UPDRSM): fold 1 saved
mean_baseline (UPDRSM): fold 2 saved
mean_baseline (UPDRSM): fold 3 saved
mean_baseline (UPDRSM): fold 4 saved
mean_baseline (UPDRSM): fold 5 saved
mean_baseline: model train complete

## 4. Multiple Linear Regression

In [6]:
train_and_save("linear_regression", make_linear_regression,
               y_updrsm, "UPDRSM")

linear_regression (UPDRSM): fold 1 saved
linear_regression (UPDRSM): fold 2 saved
linear_regression (UPDRSM): fold 3 saved
linear_regression (UPDRSM): fold 4 saved
linear_regression (UPDRSM): fold 5 saved
linear_regression: model train complete

## 5. Random Forest

In [7]:
train_and_save("random_forest", make_random_forest, 
               y_updrsm, "UPDRSM")

random_forest (UPDRSM): fold 1 saved
random_forest (UPDRSM): fold 2 saved
random_forest (UPDRSM): fold 3 saved
random_forest (UPDRSM): fold 4 saved
random_forest (UPDRSM): fold 5 saved
random_forest: model train complete

In [8]:
# hyperparameter tuning 

from sklearn.model_selection import ParameterGrid
from sklearn.metrics import mean_squared_error

# combinations to test
param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [3, 5, None],
    "model__min_samples_leaf": [2, 5]
}

tuning_results = [] # store results

for params in ParameterGrid(param_grid):
    fold_rmse = []
    
    for train_idx, val_idx in folds:
        # create new model and apply parameter combination 
        model = make_random_forest() 
        model.set_params(**params) 
        model.fit(X.iloc[train_idx], y_updrsm.iloc[train_idx])
        predictions = model.predict(X.iloc[val_idx])

        # calculate validation RMSE
        rmse = np.sqrt(mean_squared_error(y_updrsm.iloc[val_idx],predictions))

        fold_rmse.append(rmse)

    # calculate average validation RMSE across five folds.
    tuning_results.append({
        **params,
        "mean_RMSE": np.mean(fold_rmse),
        "std_RMSE": np.std(fold_rmse)
    })

rf_tuning = pd.DataFrame(tuning_results)
rf_tuning = rf_tuning.sort_values("mean_RMSE")
display(rf_tuning)

print("Best RF hyperparameters:")
display(rf_tuning.head(1))

,model__max_depth,model__min_samples_leaf,model__n_estimators,mean_RMSE,std_RMSE
7,5.0,5,200,8.123274,1.316859
11,NaN,5,200,8.123657,1.315656
3,3.0,5,200,8.145958,1.286554
10,NaN,5,100,8.209255,1.343422
6,5.0,5,100,8.209772,1.345528
1,3.0,2,200,8.212829,1.332050
2,3.0,5,100,8.225235,1.281660
0,3.0,2,100,8.276718,1.321642
5,5.0,2,200,8.322056,1.293030
9,NaN,2,200,8.326657,1.313910
4,5.0,2,100,8.425103,1.323751
8,NaN,2,100,8.433470,1.348859

Best RF hyperparameters:

,model__max_depth,model__min_samples_leaf,model__n_estimators,mean_RMSE,std_RMSE
7,5.0,5,200,8.123274,1.316859

In [ ]:
# with tuned hyperparameters
def make_tuned_rf(): # use same hyperparameter tuning for clean comparison between UPDRSM and HY
    model = make_random_forest(
        task="regression",
        n_estimators=200, 
        min_samples_leaf=5,  
        random_state=42
    )
    model.set_params(model__max_depth=5) 
    return model

train_and_save("random_forest_tuned", make_tuned_rf, y_updrsm, "UPDRSM")

random_forest_tuned (UPDRSM): fold 1 saved
random_forest_tuned (UPDRSM): fold 2 saved
random_forest_tuned (UPDRSM): fold 3 saved
random_forest_tuned (UPDRSM): fold 4 saved
random_forest_tuned (UPDRSM): fold 5 saved
random_forest_tuned: model train complete

## 6. 1D-CNN Regression
The CNN model uses 16 force-sensor channels over 1,000 time steps per subject. This is a 10-second starting window.

In [10]:
PROCESSED = ROOT/'data'/'processed'
RAW = ROOT/'data'/'raw'
TIME_STEPS = 1000
SENSOR_COLS = [f'L{i}' for i in range(1,9)] + [f'R{i}' for i in range(1,9)]

def load_signal(subject):
    csv_path = PROCESSED/f'{subject}_01.csv'
    txt_path = RAW/f'{subject}_01.txt'
    if csv_path.exists():
        walk = pd.read_csv(csv_path)
    else:
        walk = pd.read_csv(txt_path,sep=r'\s+',header=None,names=col_names)
    signal = walk[SENSOR_COLS].iloc[:TIME_STEPS].to_numpy(dtype=np.float32)
    if signal.shape != (TIME_STEPS,16) or not np.isfinite(signal).all():
        raise ValueError(f'Invalid CNN signal for {subject}: {signal.shape}')
    return signal

signals = np.stack([load_signal(subject) for subject in patients['subject']])
print('CNN input shape (subjects, time steps, channels):',signals.shape)

CNN input shape (subjects, time steps, channels): (91, 1000, 16)

In [ ]:
# train CNN model per fold, saving predictions and weights for each
import tensorflow as tf
tf.keras.utils.set_random_seed(42)
EPOCHS = 20
BATCH_SIZE = 16
for fold_number, (train_idx, val_idx) in enumerate(folds,1):
    # normalise signals 
    mean = signals[train_idx].mean(axis=(0,1),keepdims=True)
    std = np.maximum(signals[train_idx].std(axis=(0,1),keepdims=True),1e-6)
    x_train = (signals[train_idx]-mean)/std
    x_val = (signals[val_idx]-mean)/std
    
    # create and train model for each fold 
    model = build_cnn(input_shape=(TIME_STEPS,16),
                      task='regression', learning_rate = 0.001)
    model.fit(x_train,y_updrsm.iloc[train_idx].to_numpy(),
              epochs=EPOCHS,batch_size=BATCH_SIZE,verbose=1)
    

    predicted = model.predict(x_val,verbose=0).reshape(-1)
    pd.DataFrame({'subject':patients.iloc[val_idx]['subject'].to_numpy(),
                  'fold':fold_number,'actual_UPDRSM':y_updrsm.iloc[val_idx].to_numpy(),
                  'predicted_UPDRSM':predicted}).to_csv(
        OUT/'predictions'/f'cnn_val_fold{fold_number}.csv',index=False)
    model.save(OUT/'weights'/f'cnn_val_fold{fold_number}.keras')
    
    # save predictions and model weights
    np.savez(OUT/'weights'/f'cnn_val_fold{fold_number}_normalisation.npz',
             mean=mean,std=std,time_steps=TIME_STEPS,sensor_columns=np.array(SENSOR_COLS))
    print(f'Saved CNN fold {fold_number} ({len(val_idx)} predictions)')
print("CNN-1D model training complete.")

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 410.5540 - mae: 18.5496
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 383.5503 - mae: 17.7956
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 352.5683 - mae: 16.8850
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 314.0274 - mae: 15.6758
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 266.4514 - mae: 14.0876
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.2264 - mae: 12.1071
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 153.8764 - mae: 9.7495
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.0469 - mae: 7.6712
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 82.7157 - mae: 7.1103
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 84.1473 - mae: 7.5378
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.7039 - mae: 7.7381
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5525 - mae: 7.3755
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 75.5764 - mae: 6.9967
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 75.6078 - mae: 6.8723
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 77.2391 - mae: 6.8925
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.5985 - mae: 6.8856
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 76.4795 - mae: 6.8416
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 74.9617 - mae: 6.8114
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 73.8454 - mae: 6.8073
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 73.1565 - mae: 6.8176
Saved CNN fold 1 (15 predictions)
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 401.3044 - mae: 18.2277
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 378.2639 - mae: 17.5854
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 352.9754 - mae: 16.8437
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 320.6906 - mae: 15.8419
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 278.4807 - mae: 14.4458
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 225.8529 - mae: 12.5884
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 167.5029 - mae: 10.3550
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 113.9606 - mae: 8.0727
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 82.9530 - mae: 6.9002
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 82.8386 - mae: 7.4508
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 87.3886 - mae: 7.6729
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 79.9278 - mae: 7.2125
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 73.8701 - mae: 6.8102
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 74.6577 - mae: 6.7068
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 76.9409 - mae: 6.7181
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 77.0245 - mae: 6.7074
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 75.3648 - mae: 6.6646
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.7371 - mae: 6.6790
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 72.8654 - mae: 6.7304
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 72.3282 - mae: 6.7424
Saved CNN fold 2 (15 predictions)
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 471.4359 - mae: 20.2449
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 457.9606 - mae: 19.8971
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 449.3448 - mae: 19.6777
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 440.2696 - mae: 19.4457
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 426.9406 - mae: 19.1025
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 407.1086 - mae: 18.5780
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 379.7445 - mae: 17.8284
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 343.3388 - mae: 16.7793
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 295.8174 - mae: 15.2986
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 237.3322 - mae: 13.2646
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 172.7551 - mae: 10.8890
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 112.8685 - mae: 8.3646
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 74.6715 - mae: 6.7685
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 70.7948 - mae: 6.6730
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 84.8917 - mae: 7.3662
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.5532 - mae: 7.4688
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.9604 - mae: 7.0831
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 72.2359 - mae: 6.7198
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.9935 - mae: 6.5999
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.7001 - mae: 6.5786
Saved CNN fold 3 (14 predictions)
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 403.1611 - mae: 18.7179
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 384.9028 - mae: 18.2223
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 364.3658 - mae: 17.6503
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 336.2528 - mae: 16.8380
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 298.6069 - mae: 15.6870
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 251.0885 - mae: 14.1071
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 194.7793 - mae: 12.0994
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 134.9030 - mae: 9.5612
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 83.3566 - mae: 7.0707
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 57.3378 - mae: 6.0878
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 63.1780 - mae: 6.6247
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.7678 - mae: 7.0866
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68.3135 - mae: 6.8707
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 59.2772 - mae: 6.3855
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 55.9463 - mae: 6.0825
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 55.8680 - mae: 5.9856
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 55.4589 - mae: 5.9462
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54.2269 - mae: 5.8971
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 53.3010 - mae: 5.8878
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 53.2686 - mae: 5.9411
Saved CNN fold 4 (14 predictions)
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 408.9557 - mae: 18.5561
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 377.4023 - mae: 17.6831
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 344.7712 - mae: 16.7260
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 305.6731 - mae: 15.4994
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 257.9313 - mae: 13.8772
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 202.8058 - mae: 11.9000
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 145.6150 - mae: 9.7967
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 97.8255 - mae: 7.7254
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 74.8232 - mae: 6.8699
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 79.0081 - mae: 7.1718
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 84.6057 - mae: 7.4528
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 78.2159 - mae: 7.2094
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 71.5450 - mae: 6.8253
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 70.2764 - mae: 6.6908
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.1707 - mae: 6.6996
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.1310 - mae: 6.6902
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.9346 - mae: 6.6267
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68.6896 - mae: 6.5990
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68.0394 - mae: 6.6044
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 67.7227 - mae: 6.6042
Saved CNN fold 5 (14 predictions)
CNN-1D model training complete.

In [19]:
# hyperparameter tuning 
learning_rates = [0.001, 0.0001]
epoch_options = [10, 20, 30]

cnn_tuning_results = []

for learning_rate in learning_rates:
    for epochs in epoch_options:

        fold_rmse = []
        
        for fold_number, (train_idx, val_idx) in enumerate(folds):
            tf.keras.utils.set_random_seed(42)

            # nomralisation
            mean = signals[train_idx].mean(axis=(0, 1), keepdims=True)
            std = np.maximum(signals[train_idx].std(axis=(0, 1), keepdims=True), 1e-6)
            x_train = (signals[train_idx] - mean) / std
            x_val = (signals[val_idx] - mean) / std

            # build and train new cnn
            model = build_cnn(
                input_shape=(TIME_STEPS, 16),
                task="regression",
                learning_rate=learning_rate)
            
            model.fit(x_train, y_updrsm.iloc[train_idx].to_numpy(),
                epochs=epochs, batch_size=16, verbose=0)

            # generate validation predictions
            predictions = model.predict(x_val, verbose=0).reshape(-1)

            # calculate validation RMSE
            rmse = np.sqrt(mean_squared_error(y_updrsm.iloc[val_idx], predictions))
            fold_rmse.append(rmse)

        cnn_tuning_results.append({
            "learning_rate": learning_rate,
            "epochs": epochs,
            "mean_RMSE": np.mean(fold_rmse),
            "std_RMSE": np.std(fold_rmse)
        })

# compare configurations
cnn_tuning = pd.DataFrame(cnn_tuning_results)
cnn_tuning = cnn_tuning.sort_values("mean_RMSE")

display(cnn_tuning)

print("Best CNN configuration:")
display(cnn_tuning.head(1))

   learning_rate  epochs  mean_RMSE  std_RMSE
2         0.0010      30   8.671473  1.516047
1         0.0010      20   8.676058  1.468264
0         0.0010      10   9.400274  1.941435
5         0.0001      30  17.005467  1.840138
4         0.0001      20  18.688148  1.830413
3         0.0001      10  19.737863  1.814449

Best CNN configuration:

   learning_rate  epochs  mean_RMSE  std_RMSE
2          0.001      30   8.671473  1.516047

In [20]:
# CNN with tuned hyperparameters
TUNED_EPOCHS = 30
TUNED_LEARNING_RATE = 0.001
BATCH_SIZE = 16

for fold_number, (train_idx, val_idx) in enumerate(folds, 1):
    tf.keras.utils.set_random_seed(42)
    # normalisation
    mean = signals[train_idx].mean(axis=(0, 1), keepdims=True)
    std = np.maximum(signals[train_idx].std(axis=(0, 1), keepdims=True), 1e-6)
    x_train = (signals[train_idx] - mean) / std
    x_val = (signals[val_idx] - mean) / std

    # build cnn
    model = build_cnn(input_shape=(TIME_STEPS, 16), task="regression",
                      learning_rate=TUNED_LEARNING_RATE
    )

    # train and predict
    model.fit(x_train, y_updrsm.iloc[train_idx].to_numpy(),
              epochs=TUNED_EPOCHS, batch_size=BATCH_SIZE, verbose=1)

    predictions = model.predict(x_val, verbose=0).reshape(-1)

    # save output
    pd.DataFrame({
        "subject": patients.iloc[val_idx]["subject"].to_numpy(),
        "fold": fold_number,
        "actual_UPDRSM": y_updrsm.iloc[val_idx].to_numpy(),
        "predicted_UPDRSM": predictions
    }).to_csv(
        OUT / "predictions" /
        f"cnn_tuned_val_fold{fold_number}.csv",
        index=False
    )
    model.save(
        OUT / "weights" /
        f"cnn_tuned_val_fold{fold_number}.keras"
    )
    np.savez(
        OUT / "weights" /
        f"cnn_tuned_val_fold{fold_number}_normalisation.npz",
        mean=mean,
        std=std,
        time_steps=TIME_STEPS,
        sensor_columns=np.array(SENSOR_COLS)
    )

    print(f"Tuned CNN fold {fold_number} saved.")

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 410.5540 - mae: 18.5496
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 383.5503 - mae: 17.7956
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 352.5683 - mae: 16.8850
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 314.0274 - mae: 15.6758
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 266.4514 - mae: 14.0876
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.2264 - mae: 12.1071
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 153.8764 - mae: 9.7495
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 106.0469 - mae: 7.6712
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 82.7157 - mae: 7.1103
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 84.1473 - mae: 7.5378
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.7039 - mae: 7.7381
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5525 - mae: 7.3755
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 75.5764 - mae: 6.9967
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 75.6078 - mae: 6.8723
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.2391 - mae: 6.8925
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.5985 - mae: 6.8856
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 76.4795 - mae: 6.8416
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 74.9617 - mae: 6.8114
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.8454 - mae: 6.8073
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.1565 - mae: 6.8176
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 72.6216 - mae: 6.8095
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 72.1626 - mae: 6.7803
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.8415 - mae: 6.7428
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.6312 - mae: 6.7089
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.4139 - mae: 6.6877
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.1098 - mae: 6.6746
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 70.7259 - mae: 6.6656
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.3132 - mae: 6.6576
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 69.9140 - mae: 6.6504
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.5457 - mae: 6.6394
Tuned CNN fold 1 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 403.3992 - mae: 18.2852
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 377.0907 - mae: 17.5448
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 346.6328 - mae: 16.6428
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 308.4599 - mae: 15.4368
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 261.4423 - mae: 13.8351
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 206.9677 - mae: 11.8485
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 150.2888 - mae: 9.6546
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 102.8229 - mae: 7.6781
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 80.0249 - mae: 6.9733
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 82.7379 - mae: 7.4599
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.1617 - mae: 7.5729
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 77.7009 - mae: 7.1278
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 72.6804 - mae: 6.7406
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 73.4847 - mae: 6.6859
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 75.4694 - mae: 6.7328
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 75.6014 - mae: 6.7140
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 74.1958 - mae: 6.6487
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 72.7114 - mae: 6.6372
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.8323 - mae: 6.6644
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.2914 - mae: 6.6704
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.8163 - mae: 6.6453
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.5118 - mae: 6.6017
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.4430 - mae: 6.5621
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 70.4344 - mae: 6.5407
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.3042 - mae: 6.5332
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.0316 - mae: 6.5341
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.6989 - mae: 6.5391
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 69.3789 - mae: 6.5411
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 69.1031 - mae: 6.5358
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.8798 - mae: 6.5247
Tuned CNN fold 2 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 444.5095 - mae: 19.5613
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 415.2758 - mae: 18.8003
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 381.0056 - mae: 17.8646
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 338.4373 - mae: 16.6299
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 285.6765 - mae: 14.9565
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 223.7254 - mae: 12.7808
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 158.0451 - mae: 10.2906
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.8757 - mae: 7.7485
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.7414 - mae: 6.6134
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 75.7930 - mae: 7.0115
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 88.7670 - mae: 7.6096
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.0122 - mae: 7.4841
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 76.0019 - mae: 7.0278
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 72.3072 - mae: 6.7437
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0376 - mae: 6.6254
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.4513 - mae: 6.5810
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.8875 - mae: 6.5427
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.5380 - mae: 6.5536
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.1951 - mae: 6.5941
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.4341 - mae: 6.6295
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.4645 - mae: 6.6371
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 68.0837 - mae: 6.6168
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 67.5481 - mae: 6.5804
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 67.0419 - mae: 6.5423
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 66.5744 - mae: 6.5125
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 66.1402 - mae: 6.4942
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 65.7732 - mae: 6.4849
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 65.4864 - mae: 6.4831
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 65.2411 - mae: 6.4814
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 64.9860 - mae: 6.4739
Tuned CNN fold 3 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 396.4901 - mae: 18.5376
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 369.0831 - mae: 17.7794
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 337.2394 - mae: 16.8564
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 297.5208 - mae: 15.6289
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 248.6156 - mae: 13.9753
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 191.7851 - mae: 11.9176
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 132.6240 - mae: 9.4741
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 83.3315 - mae: 7.1684
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 61.1195 - mae: 6.2850
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 69.5124 - mae: 6.9643
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 78.5232 - mae: 7.3587
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 71.4800 - mae: 7.0797
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 62.5046 - mae: 6.5957
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 59.4130 - mae: 6.2481
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 59.1567 - mae: 6.1478
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 58.4314 - mae: 6.0901
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 57.0379 - mae: 6.0592
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 56.1205 - mae: 6.1030
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 56.0821 - mae: 6.1728
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 56.2374 - mae: 6.2119
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 55.9404 - mae: 6.1970
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 55.2756 - mae: 6.1425
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 54.6015 - mae: 6.0762
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54.0545 - mae: 6.0209
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 53.6034 - mae: 5.9915
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 53.2303 - mae: 5.9791
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 52.9418 - mae: 5.9756
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 52.7046 - mae: 5.9723
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.4580 - mae: 5.9632
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 52.1677 - mae: 5.9466
Tuned CNN fold 4 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 410.2703 - mae: 18.5936
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 382.8695 - mae: 17.8328
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 350.9016 - mae: 16.8976
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 311.3721 - mae: 15.6625
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 262.7931 - mae: 14.0000
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 206.4868 - mae: 11.9926
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 148.1342 - mae: 9.8763
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 99.8517 - mae: 7.8582
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 78.0587 - mae: 7.0948
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 83.8636 - mae: 7.4602
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 89.2026 - mae: 7.7660
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 82.1400 - mae: 7.4309
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 75.4994 - mae: 7.0589
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 74.4469 - mae: 6.9537
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 75.3067 - mae: 6.9580
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 75.0496 - mae: 6.9260
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 73.6766 - mae: 6.8483
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 72.4118 - mae: 6.8109
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 71.8367 - mae: 6.8355
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.5660 - mae: 6.8523
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 71.1473 - mae: 6.8394
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.6200 - mae: 6.7991
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 70.1817 - mae: 6.7543
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 69.8415 - mae: 6.7218
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 69.4988 - mae: 6.7012
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.1173 - mae: 6.6882
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68.7305 - mae: 6.6807
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68.3667 - mae: 6.6728
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68.0213 - mae: 6.6612
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 67.6847 - mae: 6.6454
Tuned CNN fold 5 saved.

## 7. Additional Severity Metric - Hoehn & Yahr

Note: Hoehn & Yahr is an ordinal classification problem, not a regression problem. The differences between stages is not necessarily equivalent to one UPDRSM point.

In [21]:
# mean baseline 
train_and_save("mean_baseline", lambda: DummyRegressor(strategy="mean"), 
               y_hy, "HoehnYahr")

mean_baseline (HoehnYahr): fold 1 saved
mean_baseline (HoehnYahr): fold 2 saved
mean_baseline (HoehnYahr): fold 3 saved
mean_baseline (HoehnYahr): fold 4 saved
mean_baseline (HoehnYahr): fold 5 saved
mean_baseline: model train complete

In [22]:
# MLR 
train_and_save("linear_regression", make_linear_regression,
                y_hy, "HoehnYahr")

linear_regression (HoehnYahr): fold 1 saved
linear_regression (HoehnYahr): fold 2 saved
linear_regression (HoehnYahr): fold 3 saved
linear_regression (HoehnYahr): fold 4 saved
linear_regression (HoehnYahr): fold 5 saved
linear_regression: model train complete

In [ ]:
train_and_save("random_forest", make_tuned_rf,
                y_hy, "HoehnYahr")

random_forest (HoehnYahr): fold 1 saved
random_forest (HoehnYahr): fold 2 saved
random_forest (HoehnYahr): fold 3 saved
random_forest (HoehnYahr): fold 4 saved
random_forest (HoehnYahr): fold 5 saved
random_forest: model train complete

In [24]:
# CNN 
HY_EPOCHS = 30
HY_LEARNING_RATE = 0.001

for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):

    tf.keras.utils.set_random_seed(42)

    # normalisation
    mean = signals[train_idx].mean(axis=(0, 1), keepdims=True)
    std = np.maximum(signals[train_idx].std(axis=(0, 1), keepdims=True), 1e-6)
    x_train = (signals[train_idx] - mean) / std
    x_val = (signals[val_idx] - mean) / std

    # build new cnn 
    model = build_cnn(
        input_shape=(TIME_STEPS, 16),
        task="regression",
        learning_rate=HY_LEARNING_RATE
    )

    # train and predict
    model.fit(x_train, y_hy.iloc[train_idx].to_numpy(),
        epochs=HY_EPOCHS, batch_size=16, verbose=1)

    predictions = model.predict(x_val, verbose=0).reshape(-1)

    # save
    pd.DataFrame({
        "subject": patients.iloc[val_idx]["subject"].to_numpy(),
        "fold": fold_number,
        "actual_HoehnYahr": y_hy.iloc[val_idx].to_numpy(),
        "predicted_HoehnYahr": predictions
    }).to_csv(
        OUT / "predictions" /
        f"cnn_HoehnYahr_val_fold{fold_number}.csv",
        index=False
    )

    model.save(
        OUT / "weights" /
        f"cnn_HoehnYahr_val_fold{fold_number}.keras"
    )

    np.savez(
        OUT / "weights" /
        f"cnn_HoehnYahr_val_fold{fold_number}_normalisation.npz",
        mean=mean,
        std=std,
        time_steps=TIME_STEPS,
        sensor_columns=np.array(SENSOR_COLS)
    )

    print(f"HoehnYahr CNN fold {fold_number} saved.")

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 3.8779 - mae: 1.9192
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.6274 - mae: 1.1672
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4681 - mae: 0.5127
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5127 - mae: 0.6064
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4791 - mae: 0.6011
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2612 - mae: 0.4005
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2360 - mae: 0.3626
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2883 - mae: 0.3970
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2870 - mae: 0.3926
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2469 - mae: 0.3670
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2229 - mae: 0.3638
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2153 - mae: 0.3618
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2004 - mae: 0.3526
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1883 - mae: 0.3395
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.1878 - mae: 0.3328
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1869 - mae: 0.3298
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1803 - mae: 0.3274
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1725 - mae: 0.3262
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1653 - mae: 0.3236
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1588 - mae: 0.3180
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1541 - mae: 0.3118
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1509 - mae: 0.3078
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1471 - mae: 0.3051
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1427 - mae: 0.3032
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1381 - mae: 0.3007
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1340 - mae: 0.2971
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1307 - mae: 0.2933
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1277 - mae: 0.2901
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1249 - mae: 0.2874
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1219 - mae: 0.2849
HoehnYahr CNN fold 1 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 3.6913 - mae: 1.8816
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5056 - mae: 1.1392
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3829 - mae: 0.4651
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4940 - mae: 0.5829
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4433 - mae: 0.5432
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2264 - mae: 0.3644
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2045 - mae: 0.3593
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2408 - mae: 0.3873
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2314 - mae: 0.3777
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1983 - mae: 0.3518
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1855 - mae: 0.3413
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1815 - mae: 0.3354
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1682 - mae: 0.3254
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1600 - mae: 0.3212
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1595 - mae: 0.3204
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1561 - mae: 0.3164
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1495 - mae: 0.3114
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1436 - mae: 0.3075
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1381 - mae: 0.3039
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.1335 - mae: 0.2994
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1307 - mae: 0.2959
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1280 - mae: 0.2945
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1246 - mae: 0.2938
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1210 - mae: 0.2925
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1178 - mae: 0.2901
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1152 - mae: 0.2874
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1132 - mae: 0.2855
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1111 - mae: 0.2841
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1089 - mae: 0.2829
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1068 - mae: 0.2814
HoehnYahr CNN fold 2 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 3.7711 - mae: 1.9026
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5153 - mae: 1.1462
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3652 - mae: 0.4818
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5603 - mae: 0.6286
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5567 - mae: 0.6099
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2886 - mae: 0.4126
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2603 - mae: 0.3899
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2837 - mae: 0.4096
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2512 - mae: 0.3824
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2151 - mae: 0.3602
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2160 - mae: 0.3656
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2161 - mae: 0.3671
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1979 - mae: 0.3516
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1865 - mae: 0.3407
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1817 - mae: 0.3337
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1740 - mae: 0.3291
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1678 - mae: 0.3279
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1640 - mae: 0.3293
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1584 - mae: 0.3243
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1529 - mae: 0.3163
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1488 - mae: 0.3109
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1448 - mae: 0.3094
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1414 - mae: 0.3093
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1383 - mae: 0.3079
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1352 - mae: 0.3038
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1325 - mae: 0.2996
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1301 - mae: 0.2971
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1280 - mae: 0.2958
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1259 - mae: 0.2939
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1240 - mae: 0.2910
HoehnYahr CNN fold 3 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 3.9323 - mae: 1.9355
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.6487 - mae: 1.1848
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4565 - mae: 0.5211
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5539 - mae: 0.6227
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5642 - mae: 0.6408
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3005 - mae: 0.4410
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2296 - mae: 0.3592
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2588 - mae: 0.3768
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2621 - mae: 0.3814
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2352 - mae: 0.3684
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2201 - mae: 0.3636
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2203 - mae: 0.3691
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2106 - mae: 0.3619
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1944 - mae: 0.3445
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1864 - mae: 0.3367
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1837 - mae: 0.3333
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1797 - mae: 0.3309
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1750 - mae: 0.3302
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1707 - mae: 0.3292
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1655 - mae: 0.3250
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1601 - mae: 0.3189
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1560 - mae: 0.3139
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1529 - mae: 0.3112
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1501 - mae: 0.3103
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1471 - mae: 0.3095
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1441 - mae: 0.3077
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1411 - mae: 0.3053
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1385 - mae: 0.3031
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1364 - mae: 0.3015
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1344 - mae: 0.3000
HoehnYahr CNN fold 4 saved.
Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3.8081 - mae: 1.9143
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5319 - mae: 1.1589
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3536 - mae: 0.4735
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5357 - mae: 0.6016
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5499 - mae: 0.6163
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2758 - mae: 0.4052
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2335 - mae: 0.3664
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2521 - mae: 0.3819
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2306 - mae: 0.3714
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1980 - mae: 0.3514
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1941 - mae: 0.3496
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1961 - mae: 0.3488
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.1819 - mae: 0.3354
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1692 - mae: 0.3271
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1637 - mae: 0.3227
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1572 - mae: 0.3170
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1508 - mae: 0.3122
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1468 - mae: 0.3094
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1423 - mae: 0.3054
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1368 - mae: 0.2991
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1324 - mae: 0.2939
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1286 - mae: 0.2911
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1252 - mae: 0.2898
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1224 - mae: 0.2884
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1197 - mae: 0.2860
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1170 - mae: 0.2827
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1148 - mae: 0.2798
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1128 - mae: 0.2779
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1110 - mae: 0.2764
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1094 - mae: 0.2745
HoehnYahr CNN fold 5 saved.